### ISSUE TITLE
或许需要一些修改。。。

### ISSUE THREAD

**Issue by Zxilly** [jiangming1399/brevent-ce-autobuild#3]
在piebridge.me中获取文件的方式可以为下载latest.apk.
应当从server.txt中检测版本
版本后缀名中多了a
git fetch可能不太好使，试试git pull+merge
我很想交PR,然而我并不会shell
手动滑稽

**Comment by jim-kirisame** [comment]
那我建议你回到上一个或者更早的版本。

使用现有的这种版本匹配方法主要是因为作者可能是先放源码再放apk的，如果直接pull下最新的源码那可能就无法正确的build。

直接下载latest可能无法判断黑域服务器的版本，暂时不考虑使用此方法。

按理说版本是从server.txt中获取的，不知你那边是出现了什么问题

**Comment by Zxilly** [comment]
emmm.非常感谢
我终于发现我build不了的原因是因为我直接git clone了代码而不是从release中下载，所以一直报错

**Comment by jim-kirisame** [comment]
emmm……按理来说用git clone才能正确的获取新版本编译来着……

**Comment by Zxilly** [comment]
作者上传时ignore了一些文件。。。所以git仓库中的代码很可能是不完整的，从release下载的比较完整（虽然我还是没编译成功Orz）

2018年1月1日 09:25，"Jim Jiang" <notifications@github.com>写道：

**Comment by jim-kirisame** [comment]
实测最新版本是没法编译通过，似乎是卡在编译后输出文件的地方。之前(不知道多久)是可以clone后编译的，也没有少啥。我建议去开个issue反应一下

**Comment by Zxilly** [comment]
我去问了。。。

   1.

   打出来的包，也无法正常运行，至少有以下问题：


   - 缺少 网络权限 声明，无法访问黑域服务，可以自行添加
   - 混淆策略不当，无法启动黑域服务，可以自行去掉 slf4j 依赖
   - 不支持 Root，可以自行修改
   - 不支持网络调试，基本无解


2018年1月1日 19:33，"Jim Jiang" <notifications@github.com>写道：

**Comment by Zxilly** [comment]
不过2.4.9是可以正常打包的，只是最后的copyReleaseApk的Task有一点小问题

2018年1月3日 13:49，"Handsome Chou" <zhouxinyu1001@gmail.com>写道：

我去问了。。。

   1.

   打出来的包，也无法正常运行，至少有以下问题：


   - 缺少 网络权限 声明，无法访问黑域服务，可以自行添加
   - 混淆策略不当，无法启动黑域服务，可以自行去掉 slf4j 依赖
   - 不支持 Root，可以自行修改
   - 不支持网络调试，基本无解


2018年1月1日 19:33，"Jim Jiang" <notifications@github.com>写道：
